# Generated by Django 4.2.26 on 2025-11-13 13:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homefeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='no-post-image', max_length=255, verbose_name='image'),
        ),
    ]
